### ISSUE TITLE
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by divyanshusahu** [egoist/feedbackok-react#3]
I am trying to use FeedbackForm react component in my existing NextJs project. But I got this error when I tried to import it.

```
./node_modules/feedbackok-react/dist/index.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
```
### My Environment

| Executable | Version |
| --------------- | ---------- |
| `npm ls next` | 9.5.1 |
| `npm ls react` | 16.13.1 |

**Comment by egoist** [comment]
Resolved in v0.1.2
